<template>
  <section class="section scale-in-center">
    <div
      class="gradani"
      style="display: flex; justify-content: center; align-items: center;"
    >
      <lottie-player
        v-show="!gallery.length"
        src="https://assets5.lottiefiles.com/datafiles/vhvOcuUkH41HdrL/data.json"
        background="transparent"
        speed="1"
        class="lottie-player"
        style="width: 100%; height: 100%;"
        loop
        autoplay
      ></lottie-player>

      <h1 v-show="!gallery.length" class="title">
        Go ahead and mint some moments!
      </h1>
      <div class="container">
        <stack
          v-if="gallery.length"
          ref="grid"
          :column-min-width="320"
          :gutter-width="15"
          :gutter-height="15"
        >
          <div class="card">
            <stack-item v-for="(image, i) in gallery" :key="i">
              <img
                :ref="`${image}${i}`"
                :src="
                  image.image.replaceAll('ipfs://', 'https://ipfs.io/ipfs/')
                "
              />
            </stack-item>
          </div>
        </stack>
      </div>

      <!-- <b-button
        class="is-primary"
        @click="images.sort(() => 0.5 - Math.random())"
        >Shuffle</b-button
      > -->
    </div>
  </section>
</template>

<script>
import { mapState } from 'vuex'
import { Stack, StackItem } from 'vue-stack-grid'
import LottiePlayer from '@lottiefiles/lottie-player'
import momintABI from '~/contracts/ABI/ERC721.json'
import { MOMINT_CONTRACT_ADDRESS } from '~/constants'

export default {
  name: 'Gallery',
  components: { LottiePlayer, Stack, StackItem },
  data() {
    return {
      gallery: [],
    }
  },

  computed: { ...mapState(['nftCollection', 'selectedAccount']) },

  watch: {
    nftCollection(newCollection) {
      this.images = newCollection
    },
  },

  async mounted() {
    this.images = this.nftCollection
    setTimeout(() => this.$refs.grid && this.$refs.grid.update(), 1000)
    this.momint = new this.$web3.eth.Contract(
      momintABI,
      MOMINT_CONTRACT_ADDRESS
    )
    await this.momint
      .getPastEvents(
        'Transfer',
        {
          filter: {
            to: await this.$web3.currentProvider.accounts[0],
          }, // Using an array means OR: e.g. 20 or 23
          fromBlock: 0,
          toBlock: 'latest',
        },
        function (error, events) {
          console.log(events)
          return events
        }
      )
      .then((events) => {
        console.log(events)
        events = events.splice(events.length - 19, events.length - 1)
        return events.map(async (event) => {
          console.log(event.returnValues.tokenId)
          const tokenMetadata = await this.momint.methods
            .tokenURI(event.returnValues.tokenId)
            .call()
          const JSONMetadata = await this.$axios.get(
            tokenMetadata.replaceAll('ipfs://', 'https://ipfs.io/ipfs/')
          )
          const image = JSONMetadata.data.image
          const name = JSONMetadata.data.name
          const desc = JSONMetadata.data.description
          this.gallery.push({ image, name, desc })
        })
      })
  },
}
</script>
<style scoped>
.title {
  font-size: 2rem;
  position: absolute;
  bottom: 26%;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-3-19 20:13:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-center {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
}
@keyframes scale-in-center {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
}
.scale-in-center {
  -webkit-animation: scale-in-center 2s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: scale-in-center 2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.gradani {
  border: 3px solid;
  padding: 2em;
  border-image-slice: 1;
  border-image-source: linear-gradient(270deg, #246655, #7957d5, #2550dd);
  -webkit-animation: animationname 30s ease infinite;
  -moz-animation: animationname 30s ease infinite;
  -o-animation: animationname 30s ease infinite;
  animation: animationname 30s ease infinite;
}
@-webkit-keyframes animationname {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}
@-moz-keyframes animationname {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}
@-o-keyframes animationname {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}
@keyframes animationname {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}
</style>
